"""Deterministic two-player data for UI and local harness smoke tests."""

from __future__ import annotations

from typing import Any

from bot.game.store import GameStore


DEMO_SESSION_ID = "demo-one-shot"
MARTIAL_PLAYER_ID = "player-martial"
CASTER_PLAYER_ID = "player-caster"


def demo_character_payloads() -> dict[str, dict[str, Any]]:
    """Return stable character payloads covering the state fields the UI renders."""
    martial = {
        "character_id": "character-martial",
        "name": "Rook Ashford",
        "class_name": "Fighter",
        "subclass_name": None,
        "ruleset_id": "srd-5.2.1",
        "alignment": "Neutral Good",
        "experience_points": 450,
        "size": "Medium",
        "heroic_inspiration": True,
        "death_saves": {"successes": 0, "failures": 0},
        "level": 2,
        "ancestry": "Human",
        "background": "Soldier",
        "hp": 17,
        "max_hp": 20,
        "temp_hp": 3,
        "armor_class": 17,
        "armor_class_calculation": {
            "base": 16,
            "use_dexterity": False,
            "dexterity_cap": None,
            "shield_bonus": 0,
            "misc_bonus": 1,
            "source_item_ids": ["item-chain-mail"],
        },
        "proficiency_bonus": 2,
        "speed": {"walk": 30},
        "proficiencies": {
            "armor": ["Light armor", "Medium armor", "Heavy armor", "Shields"],
            "weapons": ["Simple weapons", "Martial weapons"],
            "tools": ["Dice set"],
            "languages": ["Common"],
        },
        "abilities": {
            "strength": 16,
            "dexterity": 12,
            "constitution": 14,
            "intelligence": 10,
            "wisdom": 12,
            "charisma": 8,
        },
        "saving_throws": {
            "strength": 5,
            "dexterity": 1,
            "constitution": 4,
            "intelligence": 0,
            "wisdom": 1,
            "charisma": -1,
        },
        "skills": {"athletics": 5, "perception": 3, "survival": 3},
        "attacks": [
            {
                "attack_id": "longsword",
                "name": "Longsword",
                "attack_type": "melee_weapon",
                "attack_bonus": 5,
                "damage": [{"dice": "1d8", "bonus": 3, "damage_type": "slashing"}],
                "reach": 5,
                "range_normal": None,
                "range_long": None,
                "source_item_id": "item-longsword",
                "properties": ["Versatile"],
            }
        ],
        "hit_dice": {"d10": {"maximum": 2, "current": 1}},
        "spell_slots": {},
        "class_resources": {
            "second_wind": {"maximum": 2, "current": 1},
            "action_surge": {"maximum": 1, "current": 0},
        },
        "features": [
            {
                "feature_id": "fighting-style-defense",
                "name": "Fighting Style: Defense",
                "source": "Fighter 1",
                "rules_ref": "srd-5.2.1:feature:fighting-style-defense",
                "summary": "+1 AC while wearing armor.",
                "resource_key": None,
            },
            {
                "feature_id": "second-wind",
                "name": "Second Wind",
                "source": "Fighter 1",
                "rules_ref": "srd-5.2.1:feature:second-wind",
                "summary": "Recover hit points as a limited class feature.",
                "resource_key": "second_wind",
            },
            {
                "feature_id": "action-surge",
                "name": "Action Surge",
                "source": "Fighter 2",
                "rules_ref": "srd-5.2.1:feature:action-surge",
                "summary": "Take an additional action as a limited class feature.",
                "resource_key": "action_surge",
            },
        ],
        "conditions": ["Inspired"],
        "inventory": [
            {
                "item_id": "item-longsword",
                "name": "Longsword",
                "quantity": 1,
                "equipped": True,
                "notes": "Family blade",
                "rules_ref": "srd-5.2.1:weapon:longsword",
                "category": "weapon",
                "weight": 3,
            },
            {
                "item_id": "item-chain-mail",
                "name": "Chain Mail",
                "quantity": 1,
                "equipped": True,
                "notes": "",
                "rules_ref": "srd-5.2.1:armor:chain-mail",
                "category": "armor",
                "weight": 55,
            },
            {
                "item_id": "item-healing-potion",
                "name": "Potion of Healing",
                "quantity": 1,
                "equipped": False,
                "notes": "",
                "rules_ref": "srd-5.2.1:gear:potion-of-healing",
                "category": "adventuring_gear",
                "weight": 0.5,
            },
        ],
    }
    caster = {
        "character_id": "character-caster",
        "name": "Mira Vale",
        "class_name": "Wizard",
        "subclass_name": None,
        "ruleset_id": "srd-5.2.1",
        "alignment": "Chaotic Good",
        "experience_points": 300,
        "size": "Medium",
        "heroic_inspiration": False,
        "death_saves": {"successes": 0, "failures": 0},
        "level": 2,
        "ancestry": "Elf",
        "background": "Sage",
        "hp": 9,
        "max_hp": 12,
        "temp_hp": 0,
        "armor_class": 12,
        "armor_class_calculation": {
            "base": 10,
            "use_dexterity": True,
            "dexterity_cap": None,
            "shield_bonus": 0,
            "misc_bonus": 0,
            "source_item_ids": [],
        },
        "proficiency_bonus": 2,
        "speed": {"walk": 30},
        "proficiencies": {
            "armor": [],
            "weapons": ["Simple weapons"],
            "tools": [],
            "languages": ["Common", "Elvish", "Draconic"],
        },
        "abilities": {
            "strength": 8,
            "dexterity": 14,
            "constitution": 12,
            "intelligence": 16,
            "wisdom": 13,
            "charisma": 10,
        },
        "saving_throws": {
            "strength": -1,
            "dexterity": 2,
            "constitution": 1,
            "intelligence": 5,
            "wisdom": 3,
            "charisma": 0,
        },
        "skills": {"arcana": 5, "history": 5, "investigation": 5, "perception": 3},
        "attacks": [
            {
                "attack_id": "fire-bolt",
                "name": "Fire Bolt",
                "attack_type": "ranged_spell",
                "attack_bonus": 5,
                "damage": [{"dice": "1d10", "bonus": 0, "damage_type": "fire"}],
                "reach": None,
                "range_normal": 120,
                "range_long": None,
                "source_item_id": None,
                "properties": ["Cantrip"],
            }
        ],
        "hit_dice": {"d6": {"maximum": 2, "current": 2}},
        "spell_slots": {
            "1": {"maximum": 3, "current": 1},
            "2": {"maximum": 0, "current": 0},
        },
        "class_resources": {"arcane_recovery": {"maximum": 1, "current": 0}},
        "features": [
            {
                "feature_id": "arcane-recovery",
                "name": "Arcane Recovery",
                "source": "Wizard 1",
                "rules_ref": "srd-5.2.1:feature:arcane-recovery",
                "summary": "Recover expended spell slots during a rest.",
                "resource_key": "arcane_recovery",
            },
        ],
        "spellcasting": {
            "ability": "intelligence",
            "save_dc": 13,
            "attack_bonus": 5,
            "preparation_mode": "spellbook",
            "spells": [
                {
                    "spell_id": "fire-bolt",
                    "name": "Fire Bolt",
                    "level": 0,
                    "school": "Evocation",
                    "casting_time": "1 action",
                    "range": "120 feet",
                    "duration": "Instantaneous",
                    "components": ["V", "S"],
                    "concentration": False,
                    "ritual": False,
                    "rules_ref": "srd-5.2.1:spell:fire-bolt",
                    "source": "Wizard",
                },
                {
                    "spell_id": "light",
                    "name": "Light",
                    "level": 0,
                    "school": "Evocation",
                    "casting_time": "1 action",
                    "range": "Touch",
                    "duration": "1 hour",
                    "components": ["V", "M"],
                    "concentration": False,
                    "ritual": False,
                    "rules_ref": "srd-5.2.1:spell:light",
                    "source": "Wizard",
                },
                {
                    "spell_id": "mage-hand",
                    "name": "Mage Hand",
                    "level": 0,
                    "school": "Conjuration",
                    "casting_time": "1 action",
                    "range": "30 feet",
                    "duration": "1 minute",
                    "components": ["V", "S"],
                    "concentration": False,
                    "ritual": False,
                    "rules_ref": "srd-5.2.1:spell:mage-hand",
                    "source": "Wizard",
                },
                {
                    "spell_id": "detect-magic",
                    "name": "Detect Magic",
                    "level": 1,
                    "school": "Divination",
                    "casting_time": "1 action",
                    "range": "Self",
                    "duration": "Concentration, up to 10 minutes",
                    "components": ["V", "S"],
                    "concentration": True,
                    "ritual": True,
                    "rules_ref": "srd-5.2.1:spell:detect-magic",
                    "source": "Wizard",
                },
                {
                    "spell_id": "find-familiar",
                    "name": "Find Familiar",
                    "level": 1,
                    "school": "Conjuration",
                    "casting_time": "1 hour",
                    "range": "10 feet",
                    "duration": "Instantaneous",
                    "components": ["V", "S", "M"],
                    "concentration": False,
                    "ritual": True,
                    "rules_ref": "srd-5.2.1:spell:find-familiar",
                    "source": "Wizard",
                },
                {
                    "spell_id": "mage-armor",
                    "name": "Mage Armor",
                    "level": 1,
                    "school": "Abjuration",
                    "casting_time": "1 action",
                    "range": "Touch",
                    "duration": "8 hours",
                    "components": ["V", "S", "M"],
                    "concentration": False,
                    "ritual": False,
                    "rules_ref": "srd-5.2.1:spell:mage-armor",
                    "source": "Wizard",
                },
                {
                    "spell_id": "magic-missile",
                    "name": "Magic Missile",
                    "level": 1,
                    "school": "Evocation",
                    "casting_time": "1 action",
                    "range": "120 feet",
                    "duration": "Instantaneous",
                    "components": ["V", "S"],
                    "concentration": False,
                    "ritual": False,
                    "rules_ref": "srd-5.2.1:spell:magic-missile",
                    "source": "Wizard",
                },
                {
                    "spell_id": "shield",
                    "name": "Shield",
                    "level": 1,
                    "school": "Abjuration",
                    "casting_time": "1 reaction",
                    "range": "Self",
                    "duration": "1 round",
                    "components": ["V", "S"],
                    "concentration": False,
                    "ritual": False,
                    "rules_ref": "srd-5.2.1:spell:shield",
                    "source": "Wizard",
                },
                {
                    "spell_id": "sleep",
                    "name": "Sleep",
                    "level": 1,
                    "school": "Enchantment",
                    "casting_time": "1 action",
                    "range": "60 feet",
                    "duration": "Concentration, up to 1 minute",
                    "components": ["V", "S", "M"],
                    "concentration": True,
                    "ritual": False,
                    "rules_ref": "srd-5.2.1:spell:sleep",
                    "source": "Wizard",
                },
                {
                    "spell_id": "thunderwave",
                    "name": "Thunderwave",
                    "level": 1,
                    "school": "Evocation",
                    "casting_time": "1 action",
                    "range": "Self",
                    "duration": "Instantaneous",
                    "components": ["V", "S"],
                    "concentration": False,
                    "ritual": False,
                    "rules_ref": "srd-5.2.1:spell:thunderwave",
                    "source": "Wizard",
                },
                {
                    "spell_id": "identify",
                    "name": "Identify",
                    "level": 1,
                    "school": "Divination",
                    "casting_time": "1 minute",
                    "range": "Touch",
                    "duration": "Instantaneous",
                    "components": ["V", "S", "M"],
                    "concentration": False,
                    "ritual": True,
                    "rules_ref": "srd-5.2.1:spell:identify",
                    "source": "Wizard",
                },
            ],
            "known_spell_ids": ["fire-bolt", "light", "mage-hand"],
            "prepared_spell_ids": [
                "detect-magic",
                "mage-armor",
                "magic-missile",
                "shield",
                "sleep",
            ],
            "always_prepared_spell_ids": [],
            "spellbook_spell_ids": [
                "detect-magic",
                "find-familiar",
                "mage-armor",
                "magic-missile",
                "shield",
                "sleep",
                "thunderwave",
                "identify",
            ],
            "ritual_casting": True,
            "focus_item_id": "item-arcane-focus",
        },
        "conditions": ["Concentrating"],
        "inventory": [
            {
                "item_id": "item-spellbook",
                "name": "Weathered Spellbook",
                "quantity": 1,
                "equipped": True,
                "notes": "Contains prepared spells",
                "rules_ref": "srd-5.2.1:gear:spellbook",
                "category": "adventuring_gear",
                "weight": 3,
            },
            {
                "item_id": "item-component-pouch",
                "name": "Component Pouch",
                "quantity": 1,
                "equipped": True,
                "notes": "",
                "rules_ref": "srd-5.2.1:gear:component-pouch",
                "category": "adventuring_gear",
                "weight": 2,
            },
            {
                "item_id": "item-arcane-focus",
                "name": "Crystal Arcane Focus",
                "quantity": 1,
                "equipped": True,
                "notes": "",
                "rules_ref": "srd-5.2.1:gear:arcane-focus",
                "category": "spellcasting_focus",
                "weight": 1,
            },
        ],
    }
    return {MARTIAL_PLAYER_ID: martial, CASTER_PLAYER_ID: caster}


def bootstrap_demo_session(
    store: GameStore,
    *,
    session_id: str = DEMO_SESSION_ID,
) -> dict[str, Any]:
    """Create or idempotently recover a ready-to-render session at state version 5."""
    prefix = f"demo:{session_id}"
    store.create_session(
        session_id=session_id,
        idempotency_key=f"{prefix}:create",
        players=[
            {"player_id": MARTIAL_PLAYER_ID, "display_name": "Player One"},
            {"player_id": CASTER_PLAYER_ID, "display_name": "Player Two"},
        ],
        public_world={
            "campaign": {
                "campaign_id": "the-bell-beneath-briar-glen",
                "title": "The Bell Beneath Briar Glen",
                "current_scene": "rainy-square",
                "scene_title": "The Toll in the Rain",
                "summary": "A forgotten bell is stealing a village's memories one toll at a time.",
                "revealed_facts": [],
                "objectives": ["Learn what the bell is taking", "Find the missing Finn"],
            },
            "npcs": {
                "mara-finch": {
                    "name": "Mara Finch",
                    "description": "A rain-soaked lantern-maker searching for her nephew.",
                    "visible_attitude": "Frightened but hopeful",
                    "present": True,
                },
                "elian-voss": {
                    "name": "Magistrate Elian Voss",
                    "description": "An immaculate official offering a purse to destroy the bell.",
                    "visible_attitude": "Civic-minded but guarded",
                    "present": True,
                }
            },
        },
        private_world={
            "campaign": {
                "campaign_definition": "campaigns/the_bell_beneath_briar_glen.json",
                "revealed_fact_ids": [],
                "committed_clue_ids": [],
                "secrets": [
                    "The bell stores every memory it takes.",
                    "Voss removed the clapper to conceal his theft of the winter grain fund."
                ],
            },
            "npcs": {
                "mara-finch": {
                    "motives": ["Find Finn", "Protect the village"],
                    "relationship": {"trust": 1, "suspicion": 0, "fear": 2, "respect": 0},
                },
                "elian-voss": {
                    "motives": ["Destroy the bell", "Keep the grain theft secret"],
                    "relationship": {"trust": 0, "suspicion": 1, "fear": 1, "respect": 0},
                }
            },
        },
    )

    characters = demo_character_payloads()
    store.stage_character(
        session_id,
        MARTIAL_PLAYER_ID,
        character=characters[MARTIAL_PLAYER_ID],
        source="created",
        expected_version=0,
        idempotency_key=f"{prefix}:martial:stage",
    )
    store.confirm_character(
        session_id,
        MARTIAL_PLAYER_ID,
        expected_version=1,
        idempotency_key=f"{prefix}:martial:confirm",
    )
    store.stage_character(
        session_id,
        CASTER_PLAYER_ID,
        character=characters[CASTER_PLAYER_ID],
        source="imported",
        expected_version=2,
        idempotency_key=f"{prefix}:caster:stage",
    )
    store.confirm_character(
        session_id,
        CASTER_PLAYER_ID,
        expected_version=3,
        idempotency_key=f"{prefix}:caster:confirm",
    )
    store.request_roll(
        session_id,
        MARTIAL_PLAYER_ID,
        roll_kind="skill",
        check_key="athletics",
        prompt="Roll a physical d20 for Rook's Athletics check, then report only the face value.",
        dc=14,
        engine_modifier=None,
        expected_version=4,
        idempotency_key=f"{prefix}:opening-roll",
    )
    return store.get_public_session(session_id)
